// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetOverview() {
  return window['go']['main']['App']['GetOverview']();
}

export function ReloadProxy() {
  return window['go']['main']['App']['ReloadProxy']();
}

export function State() {
  return window['go']['main']['App']['State']();
}
