// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteSupplier(arg1) {
  return window['go']['main']['App']['DeleteSupplier'](arg1);
}

export function GetOverview() {
  return window['go']['main']['App']['GetOverview']();
}

export function ListRoutePolicies() {
  return window['go']['main']['App']['ListRoutePolicies']();
}

export function ListSuppliers() {
  return window['go']['main']['App']['ListSuppliers']();
}

export function ReloadProxy() {
  return window['go']['main']['App']['ReloadProxy']();
}

export function SaveRoutePolicy(arg1) {
  return window['go']['main']['App']['SaveRoutePolicy'](arg1);
}

export function SaveSupplier(arg1) {
  return window['go']['main']['App']['SaveSupplier'](arg1);
}

export function State() {
  return window['go']['main']['App']['State']();
}
