// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {supplier} from '../models';
import {routepolicy} from '../models';
import {api} from '../models';

export function CheckSupplier(arg1:string):Promise<Array<supplier.HealthRecord>>;

export function DeleteSupplier(arg1:string):Promise<Array<supplier.Record>>;

export function GetOverview():Promise<Record<string, any>>;

export function ListRoutePolicies():Promise<Array<routepolicy.Record>>;

export function ListSupplierHealth():Promise<Array<supplier.HealthRecord>>;

export function ListSuppliers():Promise<Array<supplier.Record>>;

export function ReloadProxy():Promise<Record<string, any>>;

export function SaveRoutePolicy(arg1:routepolicy.UpsertInput):Promise<Array<routepolicy.Record>>;

export function SaveSupplier(arg1:supplier.UpsertInput):Promise<Array<supplier.Record>>;

export function State():Promise<api.State>;
