// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {api} from '../models';

export function GetOverview():Promise<Record<string, any>>;

export function ReloadProxy():Promise<Record<string, any>>;

export function State():Promise<api.State>;
