package config

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/BurntSushi/toml"
)

type tomlAgent struct {
	SystemPrompt       string `toml:"system_prompt"`
	SkillsDir          string `toml:"skills_dir"`
	MaxRounds          int    `toml:"max_rounds"`
	CommandTimeout     int    `toml:"command_timeout_seconds"`
	CompactThreshold   int    `toml:"compact_threshold"`
	TranscriptDir      string `toml:"transcript_dir"`
}

type tomlAnthropic struct {
	APIKey          string `toml:"api_key"`
	BaseURL         string `toml:"base_url"`
	Model           string `toml:"model"`
	MaxTokens       int    `toml:"max_tokens"`
	EnablePromptCache  bool `toml:"enable_prompt_cache"`
	EnableThinking     bool `toml:"enable_thinking"`
	EnableStreaming    bool `toml:"enable_streaming"`
}

type tomlConfig struct {
	Agent     tomlAgent     `toml:"agent"`
	Anthropic tomlAnthropic `toml:"anthropic"`
}

func LoadTOML(workdir string) (Config, error) {
	path := filepath.Join(workdir, "config.toml")
	data, err := os.ReadFile(path)
	if err != nil {
		return Config{}, err
	}

	var raw tomlConfig
	if _, err := toml.Decode(string(data), &raw); err != nil {
		return Config{}, fmt.Errorf("invalid config.toml: %w", err)
	}

	cfg := Config{
		Workdir:            workdir,
		SystemPrompt:       raw.Agent.SystemPrompt,
		SkillsDir:          raw.Agent.SkillsDir,
		MaxRounds:          raw.Agent.MaxRounds,
		CommandTimeout:     time.Duration(raw.Agent.CommandTimeout) * time.Second,
		AnthropicAPIKey:    raw.Anthropic.APIKey,
		AnthropicBaseURL:   raw.Anthropic.BaseURL,
		AnthropicModel:     raw.Anthropic.Model,
		AnthropicMaxTokens: int64(raw.Anthropic.MaxTokens),
		EnablePromptCache:  raw.Anthropic.EnablePromptCache,
		EnableThinking:     raw.Anthropic.EnableThinking,
		EnableStreaming:    raw.Anthropic.EnableStreaming,
		CompactThreshold:   raw.Agent.CompactThreshold,
		TranscriptDir:      raw.Agent.TranscriptDir,
	}
	applyDefaults(&cfg)
	return cfg, nil
}

func GenerateDefaultTOML(workdir string) error {
	path := filepath.Join(workdir, "config.toml")
	if _, err := os.Stat(path); err == nil {
		return fmt.Errorf("config.toml already exists: %s", path)
	}

	defaults := tomlConfig{
		Agent: tomlAgent{
			SystemPrompt:     fmt.Sprintf("You are a coding agent at %s. Use tools to solve tasks.", workdir),
			SkillsDir:        "skills",
			MaxRounds:        20,
			CommandTimeout:   120,
			CompactThreshold: 50000,
			TranscriptDir:    ".transcripts",
		},
		Anthropic: tomlAnthropic{
			APIKey:          "",
			BaseURL:         "",
			Model:           "claude-opus-4-7",
			MaxTokens:       16000,
			EnablePromptCache: false,
			EnableThinking:     true,
			EnableStreaming:    true,
		},
	}

	var buf strings.Builder
	buf.WriteString("# icoo_assistant configuration\n")
	buf.WriteString("# Generated by: assistant init\n\n")
	buf.WriteString("[agent]\n")
	buf.WriteString(fmt.Sprintf("system_prompt = %q\n", defaults.Agent.SystemPrompt))
	buf.WriteString(fmt.Sprintf("skills_dir = %q\n", defaults.Agent.SkillsDir))
	buf.WriteString(fmt.Sprintf("max_rounds = %d\n", defaults.Agent.MaxRounds))
	buf.WriteString(fmt.Sprintf("command_timeout_seconds = %d\n", defaults.Agent.CommandTimeout))
	buf.WriteString(fmt.Sprintf("compact_threshold = %d\n", defaults.Agent.CompactThreshold))
	buf.WriteString(fmt.Sprintf("transcript_dir = %q\n", defaults.Agent.TranscriptDir))
	buf.WriteString("\n[anthropic]\n")
	buf.WriteString("# api_key = \"\"\n")
	buf.WriteString("# base_url = \"\"\n")
	buf.WriteString(fmt.Sprintf("model = %q\n", defaults.Anthropic.Model))
	buf.WriteString(fmt.Sprintf("max_tokens = %d\n", defaults.Anthropic.MaxTokens))
	buf.WriteString(fmt.Sprintf("enable_prompt_cache = %v\n", defaults.Anthropic.EnablePromptCache))
	buf.WriteString(fmt.Sprintf("enable_thinking = %v\n", defaults.Anthropic.EnableThinking))
	buf.WriteString(fmt.Sprintf("enable_streaming = %v\n", defaults.Anthropic.EnableStreaming))

	return os.WriteFile(path, []byte(buf.String()), 0o644)
}

func applyDefaults(cfg *Config) {
	if cfg.SystemPrompt == "" {
		cfg.SystemPrompt = fmt.Sprintf("You are a coding agent at %s. Use tools to solve tasks.", cfg.Workdir)
	}
	if cfg.SkillsDir == "" {
		cfg.SkillsDir = filepath.Join(cfg.Workdir, "skills")
	}
	if cfg.AnthropicModel == "" {
		cfg.AnthropicModel = "claude-opus-4-7"
	}
	if cfg.TranscriptDir == "" {
		cfg.TranscriptDir = filepath.Join(cfg.Workdir, ".transcripts")
	}
	if cfg.MaxRounds <= 0 {
		cfg.MaxRounds = 20
	}
	if cfg.AnthropicMaxTokens <= 0 {
		cfg.AnthropicMaxTokens = 16000
	}
	if cfg.CommandTimeout <= 0 {
		cfg.CommandTimeout = 120 * time.Second
	}
	if cfg.CompactThreshold <= 0 {
		cfg.CompactThreshold = 50000
	}
}
